language: node_js
node_js:
  - "node"
  - "7"
script:
  - yarn clean
  - yarn build
branches:
  only:
  - source
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GIT_TOKEN
  local_dir: dist
  target_branch: master
  on:
    branch: source
