language: node_js
node_js:
  - "node"
script:
  - yarn clean
  - yarn build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: bc71488ec84c6f887dbbe4f38a69b271c5f23928
  local_dir: dist
  target_branch: master
  on:
    branch: master
