language: node_js
node_js:
  - "7"
script:
  - yarn clean
  - yarn build
branches:
  only:
  - source
after_success:
  - pip install coscmd
  - coscmd -v
  - coscmd config -a $COS_SECRECT_ID -s $COS_SECRECT_KEY -b vue-homepage-1254036241 -r ap-guangzhou
  - coscmd delete -r /
  - coscmd upload dist/ /
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GIT_TOKEN
  local_dir: dist
  target_branch: master
  on:
    branch: source
